name: amlamrut
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  google_fonts: ^6.2.1
  icons_launcher: ^3.0.0
  rename_app: ^1.6.2
  flutter_animate: ^4.5.2
  flutter_typeahead: ^5.2.0
  drop_down_search_field: ^1.1.1
  dropdown_search: ^6.0.2
  shimmer: ^3.0.0
  animated_custom_dropdown: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

icons_launcher:
  image_path: "assets/images/ic_launcher.jpg"  # Path to your launcher icon image
  platforms:
    android:
      enable: true
    ios:
      enable: true